sudo: false
os: linux
dist: trusty
language: php

php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

branches:
  only:
  - master
  - /^\d+\.x$/
  - /^\d+\.\d+\.\d+$/

before_script:
- composer install --prefer-dist

script:
- mkdir -p build/logs
- php vendor/bin/phpcs
- if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml ; fi
- if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then php vendor/bin/phpunit ; fi

after_script:
- if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then travis_retry php vendor/bin/coveralls -v ; fi

cache:
  directories:
  # See https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
  - "$HOME/.composer/cache/files"
  - vendor

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: bXbulKMQgrroncVF2x8ICnvsoMbz//4nHbQa8VobAW1tWwKXeRm9g8HWI1KRL4x4qbGMCFWgAS2yxvqbwmnuY78u8aqyY9gGqNK7BFM1OnT+Hh6EduRikTPSCTaRmB4jJL0m8FEElwC9uMn2BLCYKd0Cm9fbB7GB65+mNvhxi25e0oQo+eOnd+6fA0Bk0EofkkGRr2alak2kjxOEnXXjkVV7mu9LqwJ7PmSMq/SmLh19JbfajL5qYOJgFNc/IhDGAbqw30ZmT+VtE6ZMbgPqCiAQvthc52/E36/GuiIJ8zTJKIPpwPKnYESI7OrNwOpV/VIyo1td8SIw4Kr4t2c98LqP8MW0TDRtlEaIRPeqATDazJWDUurZH/Pdu3tDplY7NLUyLiPvnhiZ5+gD5Aaw/gp+ZvCZoyEzzErso99KJIypnhxneS5xPm//0NJC2pbBt13e5DMdLsKP964xLSPjCvLqW3s9/7EDL2Lv7BUbxwvaMwy05N/XKWdKFJzyZgI4osYdoe5ammRVuskwIlClapMPRtH7Nqb/i4Lhkx34SHy6pewV/uPDMqpNAtcP3L4Vj35hAPJbQ/vexwY2ScX0ZUqfPQzq1pIegvYqxCMlaT4cKDDz6RM0JfzAkESUX+NBfJLARfVV4uPDuqV8HgHe6VWobDv2qF549Wxa8TSlBTw=
