os: linux
dist: trusty
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
    - master
    - /^\d+\.x$/
    - /^\d+\.\d+\.\d+$/

before_script:
  - composer install --prefer-dist

script:
  - make test

after_success:
  - if [[ "7.3" == "${TRAVIS_PHP_VERSION}" ]]; then bash <(curl -s https://codecov.io/bash) ; fi

cache:
  directories:
    # See https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
    - "$HOME/.composer/cache/files"
    - vendor
